### ISSUE TITLE
APK detection

### ISSUE THREAD

**Issue by phhusson** [phhusson/Superuser#15]
When su/su_sensitive are properly implemented
We might want to detect the calling APK to determine if it is supposed to be run in su or su_sensitive.
With a whitelist of apps needing su_sensitive, and a notice in the popup that the app didn't declare which sensitivity it has?

**Comment by lbdroid** [comment]
Applications shouldn't have access to sensitive at all. That is kind of the point of it, that it will only work for advanced users operating manually.

**Comment by lbdroid** [comment]
I'd be inclined to even restrict it to access through shell user and context exclusively, since I haven't been able to think of any way to enforce a manual password, except something crazy like an ASCII art captcha?

**Comment by phhusson** [comment]
I don't understand the problem with the user choosing a password himself?

You would want the users to have to select the app himself in the settings of Superuser to have the app get su_sensitive permission?

**Comment by phhusson** [comment]
Let's put this discussion in #4, and leave all discussions related to Policy.md in that #4 issue. (or it's time for a real mailing list...)
