### ISSUE TITLE
ARM64 support

### ISSUE THREAD

**Issue by toyagoton** [phhusson/Superuser#25]
So far from what it seems, there is no ARM64 support for phones such as the Samsung Galaxy S6 and S6 edge. Would it be possible to add support for ARM64?

**Comment by phhusson** [comment]
ARM64 devices are supported. (Tested on Nexus 9, Nexus 5X and a CAF 64bits device)
su is running in 32bits, but it can call 64bits executables, so it's transparent.

**Comment by toyagoton** [comment]
Wow I'm blind, sorry about that. :P
