### ISSUE TITLE
"Accept" button not usable

### ISSUE THREAD

**Issue by Mikaciu** [phhusson/Superuser#34]
Hello, 

When I try to give root access to apps, the "accept" button is not usable 2 minutes after boot time.
When I unlock the SIM card, if I'm fast enough, I can allow root access to one app, but after that, the accept button is not "touchable" anymore.

In the logs, I have : 
"Syserr : binary is old" => the error message shown on start of the superuser app
This is odd, since I flashed my boot image this morning, and reinstalled the SuperUser app from F-Droid.
PackageManager: Failure retrieving resources for me.phh.superuser: Resource ID #0x0
ResourceType : No package identifier when getting value for resource number 0x00000000

Do you know what it means ?

**Comment by phhusson** [comment]
F-Droid's SuperUser is not up-to-date, I don't know why, but that's not an actual problem.
Your problem is simply a protection: you have an application which draws an overlay on the screen (like apps which make screen yellow, or reduce brightness artificially)

**Comment by Mikaciu** [comment]
Thanks for your answer ! It was indeed Lux that was screwing with my screen...

The strange thing is that the Refuse button was still available ...

Thanks a lot !

**Comment by phhusson** [comment]
Yes, in that case, only "agree" button is blocked
