### ISSUE TITLE
Updated superuser.zip for recovery?

### ISSUE THREAD

**Issue by andoruB** [phhusson/Superuser#35]
So reading [this](https://github.com/koush/Superuser/issues/268) issue on the original Superuser git repo, I got here, and also reading issue #3 on this repo, I got to install the proper GUI app from the F-Droid repo. Now, all that is needed is to obtain an updated flashing package, so I could install Superuser off from recovery, and so I could get rid of SuperSU. Can anyone point me where I could download an updated package? And if not, could anyone instruct me (or point to a guide) how to build it off this repo on Linux?
Thanks in advance!

**Comment by phhusson** [comment]
One way of installing it is with http://superuser.phh.me/superuser.zip
Though it's not equivalent. This one is system-less, while previous one was system-only.

**Comment by andoruB** [comment]
Getting an 404 error on that page.

> This one is system-less, while previous one was system-only.

Meaning...?

**Comment by noisnogit** [comment]
I'm also getting the error saying the URL was not found in the server... :(

**Comment by breversa** [comment]
You might want to try https://superuser.phh.me/superuser.zip :-)

**Comment by noisnogit** [comment]
Loco. Thanks. Up and running =D

**Comment by Primokorn** [comment]
@andoruB systemless means that you have root access without touching the system partition.

**Comment by andoruB** [comment]
@breversa: Hadn't thought of that, thanks!

@Primokorn: thanks for the explanation :dancer: 

And ofcourse, thanks to @phhusson for being awesome, and maintaining the sole open source superuser app in the wild :D
