### ISSUE TITLE
Does it support systemless root?

### ISSUE THREAD

**Issue by yilksd** [phhusson/Superuser#36]
Several months ago Samsung note 5 needs custom kernel to root ,but then Chainfire's SuperSU provides a feature called "systemless root" (http://forum.xda-developers.com/showpost.php?p=64161125&postcount=3), which can root note 5 without custom kernel .Does this Superuser support it ?

**Comment by phhusson** [comment]
Yes it supports system-less root since october. Though the relevant part is in https://github.com/phhusson/super-bootimg

**Comment by yilksd** [comment]
http://forum.xda-developers.com/note5/general/how-to-root-note-5-t3205073   
This page says I can just  flash twrp then flash SuperSU.zip to root my note 5 with systemless root feature . I flashed twrp-2.8.7.1-nobleltezt.img using heimdall ,and then I stuck in boot loop.I could enter twrp and download mode ,but could not boot normally .Then I entered twrp and flashed your superuser.zip ,but I got only  "kernel is not seandroid enforcing" on start up screen top .Still boot loop .
Can you provide some extra information to help me root my note 5 ? Thanks .

**Comment by phhusson** [comment]
Edit the zip's config.txt, change eng to user

**Comment by yilksd** [comment]
Just changed "eng" to "user"  in the zip's config.txt ,and then flashed the superuser.zip .Still boot loop and  "kernel is not seandroid enforcing" on start up screen top .

**Comment by phhusson** [comment]
Well you just need to restore boot.img to its state before having applied my superuser.zip
Do you have a link to the kernel sources?

**Comment by yilksd** [comment]
When you boot into twrp for the first time ,it will ask you if you want to keep the system partition read-only . I chose "no" when I booted into twrp ,then I tryed to boot normally and got boot loop . I think this was the reason .
Then I restored everything and flashed twrp again. When twrp asked me ,I chose "yes' .This time  I could  boot into system successfully .
Kernel source: http://opensource.samsung.com/reception/receptionSub.do?method=sub&sub=F&searchValue=n9200
It seems my rom version is too new so there is no kernel source for my rom but only for previous versions.

**Comment by yilksd** [comment]
I changed "verity" to "noverity" in config.txt in superuser.zip and flashed it to my note5 ,then I can modify system partition without boot loop.Unfortunately I still cannot get root access.

**Comment by phhusson** [comment]
Can you test with http://phhusson.free.fr/superuser-tmp.zip ?
You'll have to delete the content of /data/security from TWRP after applying the zip

**Comment by yilksd** [comment]
After flashing superuser-tmp.zip, there was no file in /data/security ,just 2 empty folders : "aasa" and "spota". I deleted  /data/security and rebooted to system .The result is the same as superuser.zip's.

**Comment by yilksd** [comment]
I have flashed superuser-r197.zip ,rebooted to twrp,delete /data/security ,and created a new file named "security", so samsung cannot regenerate the folder. But nothing changed .The root function  still doesn't work ,and sim cards are still not detected .
How about your S6? Does the root function work on it after flashing the zip ?Can it detect sim cards?
