### ISSUE TITLE
Installation in OmniROM 6.0.1 (hammerhead)

### ISSUE THREAD

**Issue by amilopowers** [phhusson/Superuser#38]
Hello

I managed always to install SuperSU on my systems. But now I figured out that it isn't FOSS and need to change.

So here a few questions regarding your Superuser.
1. Is it compatible with Android 6+?
2. Do I first need to install the ROM (after a clean wipe?) and then flash "superuser.zip" from here ->http://superuser.phh.me/? Do I need to reboot between the installation of the ROM and flashing your zip?
3. Which Superuser app do I need to install from f-droid? I guess that one: https://f-droid.org/repository/browse/?fdfilter=superuser&fdid=me.phh.superuser

I tried it yesterday but the installation of OmniROM took forever so I restored to 5.1.1.

**Comment by phhusson** [comment]
yes, yes, no, yes :)
Please report your result

**Comment by amilopowers** [comment]
So this doesn't seem to work here.

I tried it in two ways. The first one I accicentically rebooted after flashing the ROM. So the room booted and I went back into recovery. Then I flashed the "superuser.zip" file.

That's what the terminal said:

```
Installing '/usb-otg/supersuser.zip'...
Checking for MD% file...
Skipping MD5 check: no MD5 file found
Found bootimg @ /dev/block/platform/msm_sdcc.1/by-name/boot
Generated /new-boot.img
Flashed root-ed boot.img
Updating partition details...
...done

```
I hit reboot into system and TWRP aks:

> "Youre device does not appear to be rooted. Install SuperSU now? This will root your device. 

I hit no and then the device stucks in the Omni boot animation forever. 

Same thing if I chose to flash both the OmniROM image and the superuser.zip together and try to boot into the system then. I am using TWRP 2.8.6.1 and the latest OmniROM nightly (Feb. 1st) from here: http://dl.omnirom.org/hammerhead/. Before flashing I did not only wipe but format the storage.

Is there any possibility that I have an incompatible hammerhead?

**Comment by amilopowers** [comment]
I've heard from Omni devs that your suleruser isn't supported.

Can you tell with which ROM you tested?

**Comment by phhusson** [comment]
I tested on Stock.
Can you point me to a stable OmniROM 6.0.1?

**Comment by amilopowers** [comment]
Honestly I don't know if they exist... I'll try to figure it out.

**Comment by yilksd** [comment]
@amilopowers  Did twrp ask you if you want to keep the system partition read-only ?

**Comment by amilopowers** [comment]
Yes it did. But I ditched superuser in favour of security.

**Comment by amilopowers** [comment]
@phhusson Btw: there are no stable builds of Omni they do nightlies only.

**Comment by art1fa** [comment]
For me the same, after flashing superuser.zip, OmniRom is stuck in the boot animation.

**Comment by yilksd** [comment]
@amilopowers You mean superuser is less secure than SuperSU?

**Comment by amilopowers** [comment]
Not at all. Superuse is more secure because it is open source. But in general root and superuser is a security risk and should be avoided.

**Comment by ildar** [comment]
to find out what's wrong one could enable USB ADB and install SU then get
adb log during boot loop.
