### ISSUE TITLE
Titanium Backup can't find su

### ISSUE THREAD

**Issue by mydongistiny** [phhusson/Superuser#52]
Name says it all. We added your su and all the apps I've tried work except this one. Let me know if more info is needed. Android 7.0.0_r6 angler

**Comment by phhusson** [comment]
I take it you're speaking of the AOSP release?

**Comment by mydongistiny** [comment]
Yeah. I followed the instructions to add it to AOSP, sepolicy patch etc, but used the prebuilt apk since it fails when building inline and eveything works great except TiBu. It's the only app I've come across that can't find root.

**Comment by phhusson** [comment]
Erm, could you point me to this documentation?
Integrating sepolicy via sources is unsupported ATM

**Comment by mydongistiny** [comment]
https://github.com/seSuperuser/AOSP-SU-PATCH/

**Comment by phhusson** [comment]
Oh I thought this was dead.
Well post the issue there then

**Comment by mydongistiny** [comment]
But it's su it can't find. All apps work except that one. Why would it be a problem with that?

**Comment by phhusson** [comment]
I most often have problems with SELinux policy than anything else when it comes to application compatibility.

Could you get logs? (logcat and dmesg)
