### ISSUE TITLE
Unable to remount system partition as rw after October security update

### ISSUE THREAD

**Issue by jebarb** [phhusson/Superuser#58]
Opening an issue here because XDA apparently doesn't allow new users to contribute to your development thread.

Running your su 266 in eng verity crypt hidesu mode. I've just updated to the October security patch (on angler) and can no longer modify the system partition. Attempts to remount while running through adb and a terminal throw an error saying the device is in use. If I boot into recovery (TWRP) and modify the system partition, for example, changing the hosts file, I can complete the modifications (both by flashing and manually) but they are not reflected once I boot. Quite a baffling problem as the contents of the partition are persistent among reboots between OS and recovery, but are only reflected in recovery mode.

Is this directly related to your implementation of su or is this a new restriction from the latest android update? Alternatively, am I just a moron who is doing something wrong?

Just found this link explaining the issue:
http://www.the247tech.com/android/fix-android-n-preview-root-surviving-your-trip-to-mount-doom/

Is this something you've already addressed that has been broken by the update or did it never work?

**Comment by craigacgomez** [comment]
1. Contents of the system partition remaining intact is a result of dm-verity. If you change it to nocrypt, you will be able to modify the partition and have it persist.
2. The issue with remounting system as rw is something with the toybox mount applet. If you use busybox mount, you can remount the system partition as rw.
