### ISSUE TITLE
Is this project build-able on nougat with jdk 8?

### ISSUE THREAD

**Issue by cj360** [phhusson/Superuser#64]
`jni/su/daemon.c:506:69: error: function definition is not allowed here`
`        auto void cb(void *arg, int uid, const char *src, const char *dst) {`
`                                                                           ^`
`jni/su/daemon.c:545:15: error: use of undeclared identifier 'cb'`
`        bind_foreach(cb, NULL);`
`                     ^`
`jni/su/daemon.c:549:53: error: function definition is not allowed here`
`        auto void cb(void *arg, int uid, const char *path) {`
`                                                           ^`
`jni/su/daemon.c:566:15: error: use of undeclared identifier 'cb'`
`        init_foreach(cb, NULL);`
`                     ^`
`4 errors generated.`
`make: *** [/opt/android-ndk/build/core/build-binary.mk:498: obj/local/x86/objs/su/su/daemon.o] Error 1`

Is the error I get when trying to build su on nougat with the latest ndk, and jdk 8. Is it my setup that's causing additional issues?

**Comment by craigacgomez** [comment]
It's mentioned clearly in the README

Make sure the SDK Platform for API 19 is installed, through the Android SDK Manager. Install NDK Revision 9b from here or use the latest and set NDK_TOOLCHAIN_VERSION=4.9.
