### ISSUE TITLE
--context parameter not working

### ISSUE THREAD

**Issue by lbdroid** [phhusson/Superuser#7]
From here;
https://github.com/phhusson/Superuser/commit/cea0c576a3bfbd4bb8fa66675998a938dd0d7475

Missing change required here also:
https://github.com/phhusson/Superuser/blob/master/Superuser/jni/su/su.c#L678

Should add "z:" to optstring.

**Comment by phhusson** [comment]
Oops, bad git add -p I guess.
Thanks.

**Comment by phhusson** [comment]
Ok, seeing the code, it's likely I haven't tested it.
It's also missing a break;...

**Comment by lbdroid** [comment]
Yep, that's probably why it still bailed for me when I added the z:

**Comment by lbdroid** [comment]
Works now
