### ISSUE TITLE
Copyright violation

### ISSUE THREAD

**Issue by Poussinou** [phhusson/Superuser#71]
Hi @phhusson 

I found [this app](https://play.google.com/store/apps/details?id=com.farma.superuser) on the Google Play Store. This guys just took your source code, added some ads in it and put it on the Store...

As you are the owner of the source code, feel free to open a request to google [here](https://support.google.com/legal/contact/lr_dmca?product=googleplay) to remove this false app from the Store, if it's your wish ;)

Don't forget to tell Google that:

* The app is licensed under GNU GPL v3 license and this guy is violating it;
* They are falsely claiming they made the app;
* Provide a link to this repo in the request, some screenshots of your original app...

**Comment by phhusson** [comment]
Hello,

Thanks for that report.
Even though I think this application shouldn't exist, I'm not too sure I'm in the full right to ask for a take-down.

First, I'm asking for GPL sources.
I'll see what to do after that. If the developer doesn't comply, it should be "easy"

**Comment by Poussinou** [comment]
You think the fake app is based on the old source code from @koush ?

Can you recognize if this is based on your source code or the one from Koush? (Maybe you made some UI changes, or added some new features?)

**Comment by Poussinou** [comment]
@phhusson Any news about this? Did you reported the fake app? :)

**Comment by huckleberrypie** [comment]
It's gone. ;)

**Comment by phhusson** [comment]
Cool

**Comment by Poussinou** [comment]
I'm closing this issue for now. Do not hesitate to reopen it if you find other copycats, and please copy-paste the link of this  copy here so I can track fake developers 👍 
Thanks 😃

**Comment by TacoTheDank** [comment]
he also basically plagiarized framaroot lol

https://play.google.com/store/apps/details?id=com.farmaapps.filemanager

here's his developer gmail for anyone who might want send a word: zolikwesaty@gmail.com
(not spreading of personal info. free range because its available via the app info)

**Comment by TacoTheDank** [comment]
wow this guy sucks
https://apkpure.com/developer/Farma%20Apps

"CPU-F" he didn't even try

**Comment by huckleberrypie** [comment]
@TacoTheDank Not exactly, though he is indeed cashing in on other developers' trademarks.

**Comment by Poussinou** [comment]
You can report this app to Google Play at the bottom of the page, thanks for the link :)

@phhusson If you have some time to fill the DMCA takedown request...

**Comment by Poussinou** [comment]
Everything is gone, do not hesitate to report other copycats here in the future !
