### ISSUE TITLE
About the supersu and root.

### ISSUE THREAD

**Issue by han4976** [phhusson/Superuser#77]
Hello！Phhusson.
I need you give me some help.

How can I remove the ROOT kit and SuperSU from AOSP 10/11/12 GSI images？

Help me. 
Thank you.

**Comment by JonnyTech** [comment]
Flash the secure variant, ie `system-squeak-arm64-ab-vndklite-gapps-secure.img.xz`

**Comment by han4976** [comment]
> Flash the secure variant, ie `system-squeak-arm64-ab-vndklite-gapps-secure.img.xz`

This GSI is non-root and SuperSU？
And I dont need the GAPPS.

I just need a vanilla GSI system.
No root, no supersu, no gapps.

**Comment by JonnyTech** [comment]
Yes, non-root, non-SU - there is a `vanilla` variant that has no GApps.

**Comment by JonnyTech** [comment]
https://github.com/phhusson/treble_experimentations/releases

**Comment by han4976** [comment]
Thank you.
