### ISSUE TITLE
About AOSP 10/11 Vanilla version non-root and non-gapps

### ISSUE THREAD

**Issue by han4976** [phhusson/Superuser#78]
Hello. Phhusson.
I need you some help here.

I need a vanilla version of AOSP 10 or AOSP 11 system image. 

However, I hope that this GSI image has no root, supersu and gapps.

Non-superSU, Non-root, Non-gapps on the GSI.

Which file names should I choose? So that I can download and install it.

Help me. 
Thank you.

**Comment by JonnyTech** [comment]
In PHH AOSP 10/11 you can run `Securize` in `PHH Treble Settings` to remove root/su from the GSI.

**Comment by JonnyTech** [comment]
Grab vanilla versions from here:
AOSP 11: https://github.com/phhusson/treble_experimentations/releases/tag/v313
AOSP 10: https://github.com/phhusson/treble_experimentations/releases/tag/v222

**Comment by han4976** [comment]
If I do, can it permanently remove root and supersu?

**Comment by han4976** [comment]
> Grab vanilla versions from here: AOSP 11: https://github.com/phhusson/treble_experimentations/releases/tag/v313 AOSP 10: https://github.com/phhusson/treble_experimentations/releases/tag/v222

When I clear the user data from the recovery mode and restart the system, will it remain in the non root state?

**Comment by han4976** [comment]
> In PHH AOSP 10/11 you can run `Securize` in `PHH Treble Settings` to remove root/su from the GSI.

Hello, now I have installed AOSP 11, When I try to remove root from PHH treble settings, the system prompts that a reboot is required.

However, after the system was successfully started, I found that the supersu/root was not successfully removed.

I tried three times, but failed. Cannot remove supersu/root.

**Comment by JonnyTech** [comment]
> When I clear the user data from the recovery mode and restart the system, will it remain in the non root state?

Yes, the su files will removed from the system partition by using securize

**Comment by han4976** [comment]
> > When I clear the user data from the recovery mode and restart the system, will it remain in the non root state?
> 
> Yes, the su files will removed from the system partition by using securize

When I try to remove root from PHH treble settings, the system prompts that a reboot is required.

However, after the system was successfully started, I found that the supersu/root was not successfully removed.

I tried three times, but failed. Cannot remove supersu/root.

**Comment by JonnyTech** [comment]
As you still have root, use adb or a root shell / file manager to remove these files/folders then reboot:

```
/system/bin/phh-su
/system/xbin/su
/system/etc/init/su.rc
/app/me.phh.superuser/me.phh.superuser.apk
```

**Comment by han4976** [comment]
OK, I'll try it now. 
Thank you.
